export const SITE = {
  name: 'NativeFirst',
  description: 'Crafting thoughtful, native Apple apps that feel right at home on your devices.',
  url: 'https://nativefirstapp.com',
  email: 'support@nativefirstapp.com',
  author: 'Mario',
};

export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  {
    label: 'Apps',
    href: '/apps/invoize',
    children: [
      { label: 'Invoize', href: '/apps/invoize', description: 'Professional invoices for Mac' },
      { label: 'ThinkBud', href: '/apps/thinkbud', description: 'AI learning companion for iOS' },
      { label: 'ApplyIQ', href: '/apps/applyiq', description: 'AI CV generator & interview prep' },
      { label: 'Renovise', href: '/tools/renovation-estimator', description: 'Home renovation cost estimator' },
      { label: 'PromptKit', href: '/apps/promptkit', description: 'AI prompt manager & community' },
    ],
  },
  { label: 'Blog', href: '/blog' },
  { label: 'Learn', href: '/learn' },
  { label: 'Contact', href: '/contact' },
];

export const APPS = {
  invoize: {
    name: 'Invoize',
    tagline: 'Professional invoices. Zero complexity.',
    description: 'Create beautiful, professional invoices in seconds. Designed exclusively for macOS with a native experience that feels right at home on your Mac.',
    platform: 'macOS' as const,
    status: 'available' as const,
    icon: '/images/apps/invoize-icon.png',
    appStoreUrl: 'https://apps.apple.com/app/invoize/id6758670584',
    features: [
      { title: 'Create in Seconds', description: 'Generate professional invoices with just a few clicks. No bloated forms, no unnecessary steps.', icon: 'zap' },
      { title: 'Beautiful PDF Export', description: 'Export pixel-perfect PDF invoices that look great and impress your clients.', icon: 'file' },
      { title: 'Client Management', description: 'Keep track of all your clients and their information in one organized place.', icon: 'users' },
      { title: 'Tax Calculations', description: 'Automatic tax calculations so you never have to worry about getting the numbers wrong.', icon: 'calculator' },
      { title: 'Multiple Currencies', description: 'Work with clients globally. Support for multiple currencies built right in.', icon: 'globe' },
      { title: 'Your Data Stays Local', description: 'No cloud, no subscriptions. Your invoicing data stays on your Mac, always.', icon: 'lock' },
    ],
  },
  thinkbud: {
    name: 'ThinkBud',
    tagline: 'Your AI-Powered Learning Companion.',
    description: 'Master any topic with interactive mind maps, flash cards, quizzes, and AI-powered summaries. ThinkBud turns learning into an engaging experience.',
    platform: 'iOS' as const,
    status: 'coming-soon' as const,
    icon: '/images/apps/thinkbud-icon.png',
    appStoreUrl: '#',
    features: [
      { title: 'Interactive Mind Maps', description: 'Visualize complex topics with beautiful, interactive mind maps that help you see the big picture.', icon: 'map' },
      { title: 'Smart Flash Cards', description: 'AI-generated flash cards that adapt to your learning pace and help you retain information.', icon: 'layers' },
      { title: 'Quiz Mode', description: 'Test your knowledge with auto-generated quizzes. Track your progress and identify weak spots.', icon: 'check-circle' },
      { title: 'Math Game', description: 'Make math fun with interactive games designed to sharpen your numerical skills.', icon: 'hash' },
      { title: 'AI Summaries', description: 'Get concise, intelligent summaries of any topic to jumpstart your understanding.', icon: 'book' },
      { title: 'Research Assistant', description: 'Explore topics deeper with an AI-powered research companion that finds connections.', icon: 'search' },
    ],
  },
  applyiq: {
    name: 'ApplyIQ',
    tagline: 'Land your dream job. Smarter.',
    description: 'AI-powered CV generator with 3 ATS optimization tiers — from realistic to maximum 100% match. Generate tailored CVs, then use the Interview Coach with STAR, technical, and common questions plus timed mock interviews.',
    platform: 'iOS' as const,
    status: 'available' as const,
    icon: '/images/apps/applyiq-icon.png',
    appStoreUrl: 'https://apps.apple.com/app/applyiq/id6759157564',
    features: [
      { title: 'Base CV Builder', description: 'Enter your CV manually or paste and upload it. Add personal info, professional summary, and experience — your starting point for every application.', icon: 'clipboard' },
      { title: '3-Tier CV Generation', description: 'Choose from three ATS match levels — from a realistic match to a maximum 100% ATS score. You control how aggressive the optimization is.', icon: 'target' },
      { title: 'Interview Coach', description: 'A full interview preparation suite with four tabs: Overview, Common, STAR, and Technical — each with role-specific questions and difficulty ratings.', icon: 'bar-chart' },
      { title: 'STAR Method Breakdown', description: 'Each STAR question comes with a complete Situation, Task, Action, Result breakdown color-coded for easy practice.', icon: 'pen-tool' },
      { title: 'Mock Interview', description: '15 timed questions at 2 minutes each. Answer in real-time and rate yourself after every response to track your confidence.', icon: 'message-circle' },
      { title: 'Privacy by Design', description: 'Your career data stays on your device. No cloud uploads, no data selling. Ever.', icon: 'shield' },
    ],
  },
  renovise: {
    name: 'Renovise',
    tagline: 'Know what it costs. Before you commit.',
    description: 'Free home renovation cost estimator with data-backed estimates for any room. Regional pricing, cost breakdowns, ROI insights — all on your iPhone, no signup required.',
    platform: 'iOS' as const,
    status: 'available' as const,
    icon: '/images/apps/renovise-icon.svg',
    appStoreUrl: 'https://apps.apple.com/app/renovise/id6759835211',
    features: [
      { title: 'Instant Estimates', description: 'Get budget, mid-range, and premium cost ranges in seconds for 9 room types and 4 scope levels.', icon: 'zap' },
      { title: 'Regional Pricing', description: 'Costs adjusted by ZIP code. NYC is 45% above average, Houston 5% below — your estimate reflects that.', icon: 'globe' },
      { title: 'Cost Breakdown', description: 'See where your money goes — labor, materials, fixtures, permits — with percentage breakdowns.', icon: 'calculator' },
      { title: 'Shopping Lists', description: 'Every material priced and organized. Take it to the store or share with your contractor.', icon: 'file' },
      { title: 'AI Room Scanner', description: 'Snap a photo of your room and get a smarter, more accurate estimate automatically.', icon: 'zap' },
      { title: 'Your Data Stays Local', description: 'No cloud, no accounts, no data collection. Your renovation plans stay on your phone.', icon: 'lock' },
    ],
  },
  promptkit: {
    name: 'PromptKit',
    tagline: 'Your prompts. Organized. Shared. Launched.',
    description: 'Save, organize, and launch AI prompts directly to ChatGPT, Claude, Gemini, and more. Build workflows, share with the community, and never lose a prompt again.',
    platform: 'iOS' as const,
    status: 'coming-soon' as const,
    icon: '/images/apps/promptkit-icon.svg',
    appStoreUrl: '#',
    features: [
      { title: 'Prompt Library', description: 'Save all your best prompts in one place. Search, tag, categorize, and find any prompt instantly — no more digging through chat histories.', icon: 'library' },
      { title: 'Variable System', description: 'Add {{placeholders}} to any prompt. Fill in the blanks before launch — turn one prompt into a reusable template for any context.', icon: 'variable' },
      { title: 'Launch to Any AI', description: 'Send prompts directly to ChatGPT, Claude, Gemini, Perplexity, or Copilot with one tap. Deep links, web, or clipboard — whatever works.', icon: 'launch' },
      { title: 'Workflow Builder', description: 'Chain prompts into multi-step workflows. Research → Draft → Polish — run them step by step with the right AI for each stage.', icon: 'workflow' },
      { title: 'Community Feed', description: 'Browse trending prompts from other users. Save the best ones to your library, share yours with the world, and discover workflows you never thought of.', icon: 'community' },
      { title: 'Cloud Sync', description: 'Your prompts everywhere. Real-time sync across iPhone and Mac with offline-first design — works without internet, syncs when connected.', icon: 'sync' },
      { title: 'Keyboard Extension', description: 'Access your entire prompt library from any app on iPhone and iPad. No switching apps — your prompts are always one tap away on the keyboard.', icon: 'keyboard' },
      { title: 'Quick Actions & Menu Bar', description: 'Long-press the app icon for instant actions — New Prompt, Search, Workflows. On Mac, the menu bar gives you lightning-fast access without opening the full app.', icon: 'quickaction' },
      { title: 'Face ID Protection', description: 'Lock PromptKit behind Face ID for an extra layer of privacy. Your prompts may contain sensitive business data — keep them secure.', icon: 'faceid' },
      { title: 'Built for Everyone', description: 'Full VoiceOver support, Dynamic Type, high-contrast mode, and reduced motion. PromptKit is designed to be usable by everyone, not just some people.', icon: 'accessibility' },
    ],
  },
};

export const COURSE = {
  slug: 'vibe-code-native',
  title: 'Vibe Code Native',
  subtitle: 'Build Real iOS Apps with AI',
  description: 'A free, comprehensive course teaching iOS developers how to leverage AI tools — especially Claude Code — to build production-quality native apps faster.',
  author: 'Mario',
  isPremium: false,
  totalLessons: 21,
  modules: [
    {
      number: 1,
      title: 'Introduction to Vibe Coding',
      description: 'Understand the AI-assisted development landscape, choose the right tools, and write your first prompt.',
      lessonCount: 3,
    },
    {
      number: 2,
      title: 'Prompting for Swift & SwiftUI',
      description: 'Master the art of writing effective prompts, configure CLAUDE.md, and avoid the most common mistakes.',
      lessonCount: 4,
    },
    {
      number: 3,
      title: 'Your First App — Todo App with AI',
      description: 'Put everything into practice by building a complete Todo app from scratch — planning, data layer, views, and polish.',
      lessonCount: 4,
    },
    {
      number: 4,
      title: 'Real-World Patterns',
      description: 'Networking, error handling, navigation, and system framework integration — the patterns every real app needs.',
      lessonCount: 4,
    },
    {
      number: 5,
      title: 'Testing & Quality',
      description: 'Unit testing with AI, debugging techniques, and code review workflows that catch bugs before your users do.',
      lessonCount: 3,
    },
    {
      number: 6,
      title: 'Ship It — From Code to App Store',
      description: 'Performance optimization, accessibility, localization, and everything you need to launch on the App Store.',
      lessonCount: 3,
    },
  ],
};

export const PREMIUM_COURSE = {
  slug: 'ship-native',
  title: 'Ship Native',
  subtitle: 'Build a Production iOS App with AI in 24 Hours',
  description: 'Build "BetAway" — a free gambling recovery app for iOS — from zero to App Store. Master Swift 6, SwiftUI, SwiftData, Charts, WidgetKit, App Intents, and on-device ML through hands-on, prompt-driven lessons. You learn to code — and build something that helps people.',
  author: 'Mario',
  isPremium: true,
  price: 79,
  totalLessons: 26,
  modules: [
    {
      number: 1,
      title: 'Project Foundation',
      description: 'Set up the Xcode project, define your architecture with MVVM + Repository, model your data layer with SwiftData, and write a CLAUDE.md that keeps AI on track.',
      lessonCount: 3,
    },
    {
      number: 2,
      title: 'Core UI with SwiftUI',
      description: 'Build a design system, recovery dashboard, check-in flow with haptic feedback, and a Router-based navigation architecture.',
      lessonCount: 4,
    },
    {
      number: 3,
      title: 'Data Layer & Persistence',
      description: 'Implement protocol-based repositories, complex SwiftData queries with predicates, and a migration strategy that protects user data.',
      lessonCount: 3,
    },
    {
      number: 4,
      title: 'AI Integration',
      description: 'Add on-device ML with NaturalLanguage, build a sentiment analysis engine for journal entries, and create a CBT-powered insights system.',
      lessonCount: 3,
    },
    {
      number: 5,
      title: 'System Frameworks',
      description: 'Visualize recovery streaks with Charts, create a WidgetKit home screen widget, and integrate Siri Shortcuts through App Intents.',
      lessonCount: 3,
    },
    {
      number: 6,
      title: 'Quality & Testing',
      description: 'Write AI-generated unit tests, automate UI testing, and master the Instruments debugging workflow.',
      lessonCount: 3,
    },
    {
      number: 7,
      title: 'Production Polish',
      description: 'Handle errors gracefully, add VoiceOver and localization support, and optimize performance for a smooth user experience.',
      lessonCount: 3,
    },
    {
      number: 8,
      title: 'Ship It',
      description: 'Prepare App Store assets, set up CI/CD with GitHub Actions, and distribute through TestFlight.',
      lessonCount: 2,
    },
    {
      number: 9,
      title: 'Bonus — Advanced Patterns',
      description: 'CloudKit sync for multi-device support and a Share Extension for quick recovery check-ins from anywhere.',
      lessonCount: 2,
    },
  ],
};

export const COURSES: Record<string, typeof COURSE | typeof PREMIUM_COURSE> = {
  'vibe-code-native': COURSE,
  'ship-native': PREMIUM_COURSE,
};

export function getCourseBySlug(slug: string) {
  return COURSES[slug] ?? null;
}

export const BLOG_TAGS = [
  'All',
  'Development',
  'AI',
  'Apple',
  'Vibe Coding',
  'SwiftUI',
  'Announcements',
] as const;

export const AUTHORS: Record<string, { role: string; bio: string }> = {
  'Mario': {
    role: 'Founder & CEO',
    bio: 'Founder of NativeFirst. Building native Apple apps with SwiftUI and a passion for great user experiences.',
  },
  'Emily Chen': {
    role: 'Lead Designer',
    bio: 'Lead designer at NativeFirst. Focused on creating intuitive, beautiful interfaces that feel native to every Apple platform.',
  },
  'James Walker': {
    role: 'iOS Engineer',
    bio: 'iOS engineer at NativeFirst. SwiftUI enthusiast, open-source contributor, and performance optimization nerd.',
  },
  'Rachel Torres': {
    role: 'Content & Research',
    bio: 'Content strategist at NativeFirst. Researching the intersection of technology, mental health, and user advocacy.',
  },
  'NativeFirst R Team': {
    role: 'Research Team',
    bio: 'The NativeFirst Research Team. We dig through the noise so you get the signal. Opinions are our own, coffee is mandatory.',
  },
  'NativeFirst Team': {
    role: 'The Team',
    bio: 'The whole NativeFirst crew. We build native Apple apps, argue about tabs vs spaces, and occasionally write things that aren\'t code.',
  },
};

export interface BlogComment {
  author: string;
  date: string;
  text: string;
}

export interface BlogEngagement {
  likes: number;
  comments: BlogComment[];
}

export const BLOG_ENGAGEMENT: Record<string, BlogEngagement> = {
  'hello-world': {
    likes: 24,
    comments: [
      { author: 'David Kim', date: '2025-02-08', text: 'Great intro! Love the focus on native development. Looking forward to seeing what you build.' },
      { author: 'Sophie Laurent', date: '2025-02-10', text: 'Finally a company that puts native first. The web wrapper trend needs to stop.' },
    ],
  },
  'vibe-coding-ios-comprehensive-analysis': {
    likes: 89,
    comments: [
      { author: 'Alex Rivera', date: '2026-02-14', text: 'This is exactly how I feel about SwiftUI + AI. The combo is incredible for productivity.' },
      { author: 'Marcus Webb', date: '2026-02-15', text: 'Tried vibe coding last week after reading this. Game changer for prototyping. Built a full CRUD app in one afternoon.' },
      { author: 'Tara Singh', date: '2026-02-16', text: 'Great writeup Mario. Quick question — when you send commands from your phone via Claude mobile, does it actually commit directly to your repo or do you review first?' },
      { author: 'Mario', date: '2026-02-16', text: 'Thanks Tara! So by default it pushes to a branch, not directly to main. I usually send something like "create a new feature branch and build X" from my phone, then when I get to my desk I review the diff, test it in Xcode, and merge. You always stay in control of what actually lands.' },
      { author: 'Jake Morrison', date: '2026-02-17', text: 'Honest question — do you ever worry about becoming too dependent on AI? Like what happens when Claude is down or you hit rate limits mid-session?' },
      { author: 'Mario', date: '2026-02-17', text: 'Totally fair question Jake. Short answer: no, because vibe coding doesn\'t replace knowing how to code. It replaces the tedious parts. When Claude is down (happened twice in 3 months), I just... write code manually. It\'s slower but I still know how. Think of it like GPS — if it dies you can still read a map, you just don\'t want to lol.' },
      { author: 'Nina Kowalski', date: '2026-02-18', text: 'The Worker feature is wild. I set it up to refactor my entire networking layer while I was in a meeting. Came back to 23 files changed, all tests passing. Felt like having an intern that actually knows what they\'re doing.' },
      { author: 'David Park', date: '2026-02-19', text: 'Have you tried using Claude Code with a CLAUDE.md file for project-specific rules? Curious if that makes a big difference for iOS projects specifically.' },
      { author: 'Mario', date: '2026-02-19', text: 'David — yes and it\'s honestly a must. Our CLAUDE.md has stuff like "always use @Observable instead of ObservableObject", "prefer NavigationStack over NavigationView", "use Swift Testing not XCTest for new tests". It\'s like giving Claude a style guide for your project. We actually have a whole lesson on this in the course if you want to go deeper.' },
      { author: 'Samira Hassan', date: '2026-02-20', text: 'This convinced me to switch from Cursor to Claude Code. One week in and the difference in SwiftUI output quality is night and day. Cursor kept mixing UIKit patterns into my SwiftUI code and it was driving me crazy.' },
      { author: 'Leo Tanaka', date: '2026-02-21', text: 'Okay but real talk — the pricing. Claude Max is not cheap. For indie devs trying to bootstrap, is Kiro genuinely good enough or is it a "you get what you pay for" situation?' },
      { author: 'Mario', date: '2026-02-22', text: 'Real talk back Leo — Kiro + Opus is genuinely solid for like 90% of what you need. The main things you miss are the Worker (background tasks) and mobile commands. If you\'re an indie dev building your first app, start with Kiro, ship it, and upgrade to Claude Code when the app makes money. No point burning cash before you have revenue.' },
      { author: 'Rachel Kim', date: '2026-02-23', text: 'The "ideas don\'t wait for you to be at your desk" part really hit home. I\'ve lost so many feature ideas because by the time I sat down to code them I forgot the details or lost the motivation. Being able to just fire off a prompt from the couch is a game changer.' },
      { author: 'Ben Okafor', date: '2026-02-25', text: 'Just finished reading this for the second time. First time I was skeptical, tried it for two weeks, and now I\'m back to say you understated it if anything. Opus 4.6 is absurd for Swift. It nailed a complex CoreData + CloudKit sync on the first try that took me 3 days to write manually last year.' },
    ],
  },
  'building-native-apps': {
    likes: 35,
    comments: [
      { author: 'Nathan Brooks', date: '2025-02-26', text: 'The performance argument alone is worth the read. Native apps just feel different.' },
      { author: 'Olivia Park', date: '2025-02-28', text: 'Shared this with my team. We are finally reconsidering our cross-platform approach.' },
    ],
  },
  'abnetworking-modern-ios-networking': {
    likes: 18,
    comments: [
      { author: 'Chris Lawson', date: '2025-03-05', text: 'ABNetworking has saved me hours of boilerplate. The async/await integration is really clean.' },
      { author: 'Priya Mehta', date: '2025-03-07', text: 'Great walkthrough James. Already using this in production.' },
    ],
  },
  'absecurescreen-ios-security-sdk': {
    likes: 22,
    comments: [
      { author: 'Tyler Morrison', date: '2025-03-12', text: 'Every banking app needs this. The screenshot protection alone is worth integrating.' },
      { author: 'Lisa Wang', date: '2025-03-14', text: 'Implemented ABSecureScreen in our fintech app last week. Works flawlessly.' },
    ],
  },
  'how-ats-systems-work-applyiq': {
    likes: 57,
    comments: [
      { author: 'Jordan Ellis', date: '2026-02-16', text: 'I had no idea ATS systems rejected 75% of applications automatically. This explains so much about my job search.' },
      { author: 'Amanda Foster', date: '2026-02-17', text: 'The 3-tier approach is brilliant. Most tools just blast keywords everywhere.' },
      { author: 'Ryan Cooper', date: '2026-02-18', text: 'Sent this to three friends who are job hunting right now. Eye-opening.' },
    ],
  },
  'why-we-built-invoize': {
    likes: 31,
    comments: [
      { author: 'Emma Richardson', date: '2026-02-15', text: 'As a freelancer, this is exactly what I needed. Simple, no subscription, native Mac app.' },
      { author: 'Michael Torres', date: '2026-02-17', text: 'Payment reminders will be a game changer. Any ETA on that feature?' },
    ],
  },
  'claude-code-remote-control-game-changer': {
    likes: 134,
    comments: [
      { author: 'Kevin Zhao', date: '2026-02-26', text: 'Tried this within 20 minutes of reading the post. Sent a command from my phone to add a dark mode toggle. Got home, opened Xcode — the toggle was there, wired up, working. I literally laughed out loud. This is insane.' },
      { author: 'Daniela Furst', date: '2026-02-26', text: 'As an OpenClaw contributor I want to push back a little. The Docker isolation isn\'t a bug, it\'s a feature — you don\'t want an AI agent with unrestricted access to your filesystem. That said... the developer experience you describe here is clearly better for coding specifically. Fair article overall.' },
      { author: 'Mario', date: '2026-02-26', text: 'Daniela — totally respect that perspective and I should\'ve been clearer: Docker isolation makes complete sense for a general-purpose agent. If OpenClaw is managing my smart home or running web scrapers I absolutely want sandboxing. The issue is specifically when you\'re trying to do real development work on your actual project. Different use case, different requirements.' },
      { author: 'Tomás Herrera', date: '2026-02-26', text: 'The grocery store story is so relatable it hurts. I have 200+ notes in Apple Notes that say things like "refactor UserManager" with zero context. Half of them are from 2024. This might actually fix my brain.' },
      { author: 'Sarah Lindqvist', date: '2026-02-26', text: 'Hot take: the OpenClaw section is unnecessarily harsh. Peter built something incredible and open-source. Claude Code is a paid product from a $60B company. Comparing them like they\'re in the same weight class feels unfair.' },
      { author: 'Mario', date: '2026-02-26', text: 'Sarah — fair criticism and I hear you. Peter is genuinely brilliant and OpenClaw pushed the entire industry forward. My point isn\'t that OpenClaw is bad — it\'s that for the specific use case of writing production code from your phone, Claude Code solved it in a way that OpenClaw\'s architecture can\'t match. OpenClaw is still incredible for automation, home stuff, and general agent tasks. Different tools, different strengths.' },
      { author: 'James Whitfield', date: '2026-02-26', text: 'Question from a paranoid backend dev: when you send a command from your phone, what exactly travels over the network? The full prompt? Does Anthropic see it? Is there E2E encryption between the phone and your Mac?' },
      { author: 'Mario', date: '2026-02-26', text: 'James — your prompt goes through Anthropic\'s API (same as using Claude Code normally). So Anthropic processes it, yes. The actual code changes happen locally on your machine. Your source code doesn\'t get uploaded. If you\'re building classified stuff, check their data retention policy, but for normal dev work the security model is solid.' },
      { author: 'Priya Narayanan', date: '2026-02-26', text: 'Showed this to my CTO. His first reaction: "this can\'t be real." His reaction 30 minutes later after setting it up: "cancel my afternoon meetings." We\'re rolling this out to the whole iOS team next week.' },
      { author: 'Chris Müller', date: '2026-02-26', text: '19 min read and I didn\'t skip a single paragraph. The WhatsApp vs purpose-built interface comparison is spot on. I tried using OpenClaw for coding through Telegram and the experience was... not great. Finding old commands between random messages was a nightmare.' },
      { author: 'Aisha Okonkwo', date: '2026-02-27', text: 'Just set up remote control this morning. Sent my first command from the bus: "add pull-to-refresh to the TransactionsListView with a haptic feedback on completion." Got to the office and it was done, tests and all. I am not okay. In a good way.' },
      { author: 'Dylan Park', date: '2026-02-27', text: 'The part about Peter leaving for OpenAI felt like a low blow tbh. People change jobs for all kinds of reasons. Doesn\'t mean the project is dead — Linux survived Torvalds taking breaks.' },
      { author: 'Mario', date: '2026-02-27', text: 'Dylan — you\'re right, that section could\'ve been more nuanced. People leave for many reasons and it doesn\'t invalidate the project. I mentioned it because I think it\'s relevant context, not as a death sentence. OpenClaw\'s community is strong and will keep it going. My bad if it came across as a cheap shot.' },
      { author: 'Nadia Petrova', date: '2026-02-27', text: 'The "Swiss Army knife vs proper knife" metaphor is perfect. I use OpenClaw daily for home automation and it\'s phenomenal for that. But every time I tried to use it for actual Swift development the Docker isolation killed me. Different tools for different jobs.' },
      { author: 'Marcus Chen', date: '2026-02-27', text: 'Okay I was skeptical but then I timed it. Old workflow: open laptop, wait for Xcode, create branch, write code, build, test, commit = 45 min minimum. New workflow: phone command on the toilet = 30 seconds of my time. The future is weird and I\'m here for it.' },
      { author: 'Elise Johansson', date: '2026-02-27', text: 'The security point about ClawHub is really important and I wish more people talked about it. We audited three popular OpenClaw skills at my company and found two that were making network calls to endpoints not mentioned in their descriptions. Pulled them immediately.' },
      { author: 'Ravi Kapoor', date: '2026-02-27', text: 'Follow-up question Mario: does remote control work if your Mac goes to sleep? Or do you need to disable sleep/use Amphetamine? Asking because my MacBook Air is aggressive about sleeping when I close the lid.' },
      { author: 'Mario', date: '2026-02-27', text: 'Ravi — good catch. Your Mac needs to stay awake for the session to stay alive. I use Amphetamine (free on the App Store) and just set it to keep awake while Claude Code is running. If your Mac does sleep, the session disconnects but you can reconnect when it wakes up. Not ideal but manageable.' },
    ],
  },
  'open-source-dying-vibe-coding': {
    likes: 47,
    comments: [
      { author: 'Tom Ashworth', date: '2026-02-28', text: 'I maintain a Swift package with ~2k stars. Got 14 PRs last week. Twelve were AI slop. The other two were actually good. Took me longer to close the twelve than it would\'ve taken to write the damn fixes myself. This post is painfully accurate.' },
      { author: 'Jessica Huang', date: '2026-02-28', text: 'The Tailwind story made me genuinely angry. 75 million monthly downloads and the guy can\'t pay his team. Meanwhile Copilot is making bank off the docs his team wrote. Cool cool cool.' },
      { author: 'Marco Bellini', date: '2026-02-28', text: 'Wait so you guys love Claude Code, you wrote like three glowing articles about vibe coding, and now you\'re saying it\'s killing open source? Pick a lane lol' },
      { author: 'NativeFirst', date: '2026-02-28', text: 'Marco — lol fair. But a hammer isn\'t evil just because someone used it to break a window, right? We use Claude Code in our own codebase where we understand the architecture and actually review the output. That\'s wildly different from people yeet-ing AI-generated PRs at strangers\' repos and ghosting. Same tool, completely different behavior.' },
      { author: 'Dana Kessler', date: '2026-02-28', text: '19% slower but FELT 20% faster. That\'s not a productivity tool, that\'s a placebo with a subscription plan. I laughed, then I got sad, then I checked my own Cursor stats. I don\'t want to talk about it.' },
      { author: 'Alex Petrov', date: '2026-02-28', text: 'We just started requiring Open Source Pledge contributions from every team that uses OSS at my company. Which is... every team. It\'s not a lot per project but it adds up. More companies need to stop freeloading.' },
      { author: 'Sana Mirza', date: '2026-02-28', text: 'Surprised you didn\'t mention the matplotlib incident. An AI agent literally wrote and published a blog post ATTACKING the maintainer who rejected its PR. We are so unbelievably cooked.' },
      { author: 'NativeFirst', date: '2026-02-28', text: 'Sana — oh we know about the matplotlib thing. Scott Shambaugh rejected an AI agent\'s PR and the thing autonomously published a 1,500-word hit piece attacking him. We left it out because the post was already a novel, but honestly it deserves its own article. The "AI retaliates against human who said no" genre is not where we expected 2026 to go.' },
      { author: 'Patrick Dunn', date: '2026-02-28', text: 'Just started learning iOS dev and this article lowkey terrifies me. If Stack Overflow dies and docs traffic drops, where exactly do beginners learn? From the same AI that confidently hallucinates APIs that don\'t exist?' },
      { author: 'Leah Torres', date: '2026-02-28', text: 'The Ruiz quote about "value of external contribution is probably less than zero" made me genuinely sad. I got my first job because a maintainer noticed my PR. That path might just not exist anymore for the next generation of developers. That sucks.' },
      { author: 'Raj Sharma', date: '2026-02-28', text: 'METR used Cursor + Claude 3.5 Sonnet though. Opus 4.6 is a completely different animal. Would love to see them rerun it — bet the productivity number flips positive.' },
      { author: 'NativeFirst', date: '2026-02-28', text: 'Raj — yeah METR themselves called it a snapshot of early-2025 tools and Opus 4.6 is way better. But here\'s the thing: even if the productivity number goes positive, the open source crisis doesn\'t go away. Faster AI = more PRs generated faster = more garbage for maintainers to review. The speed of the tool doesn\'t fix the incentive problem.' },
      { author: 'Natalie Eriksson', date: '2026-02-28', text: 'Best thing I\'ve read in weeks. Shared with my entire eng team. The "graffiti with a fancier spray can" line is going directly into my Slack status.' },
    ],
  },
  'home-renovation-costs-2026-what-to-expect': {
    likes: 72,
    comments: [
      { author: 'Jake Holloway', date: '2026-03-02', text: 'I was one of those 130 comments on the Reddit thread. My story: quoted $35k for a kitchen remodel in Denver, another guy said $18k for the same scope. Ended up going with the $18k guy. He did a great job. The $35k quote was just... greed? I still don\'t understand the pricing in this industry.' },
      { author: 'Michelle Tran', date: '2026-03-02', text: 'The "19% stopped halfway through" stat physically hurt me. That was us last year. Half-demolished master bath for THREE MONTHS because the contractor found knob-and-tube wiring behind the wall and suddenly it was an extra $12k we didn\'t have. Three months of showering in the guest bathroom while staring at exposed studs.' },
      { author: 'Carlos Mendez', date: '2026-03-02', text: 'Signing up to test this immediately. I\'m about to start a full kitchen reno and every contractor gives me a different number with zero explanation of why. It\'s like buying a car except the car has no sticker price and the salesman won\'t tell you what the engine costs separately from the wheels.' },
      { author: 'NativeFirst', date: '2026-03-02', text: 'Carlos — that car analogy is perfect, we\'re stealing it. Imagine walking into a dealership and getting quotes of $20k, $35k, and $52k for the same car. You\'d think you were being pranked. But that\'s literally what happens with renovation quotes and everybody just... accepts it? Renovise just went live on the App Store — US only for now. Go try it.' },
      { author: 'Sarah Chen', date: '2026-03-02', text: '114k views on r/HomeImprovement is insane for a text post. That subreddit is normally just people asking about grout and arguing about HVAC brands. You clearly hit the exact nerve that everyone pretends doesn\'t exist.' },
      { author: 'Derek Williams', date: '2026-03-02', text: 'The 78% exceed budget number is wild but honestly tracks with my experience. We budgeted $40k for our bathroom + bedroom reno. Final cost: $61k. The "little things" add up in a way nobody warns you about — permits, dumpster rental, temporary fixtures, eating out every night because your kitchen is a construction zone.' },
      { author: 'Lisa Kowalczyk', date: '2026-03-02', text: 'I work as a project manager for a GC. The pricing gap isn\'t always about scamming — different contractors have different overhead, insurance costs, crew quality, and timelines. A $22k quote might include permits, cleanup, and a 2-year warranty. The $8k guy might be a handyman with no insurance who\'ll ghost you if the tile cracks. The problem is homeowners have NO WAY to know which is which.' },
      { author: 'NativeFirst', date: '2026-03-02', text: 'Lisa — this is exactly the kind of context we want Renovise to provide. You\'re right that not all expensive quotes are ripoffs and not all cheap quotes are scams. The goal is to give homeowners a baseline so they can have an informed conversation instead of just guessing. Knowing what materials + labor should cost in your area lets you ask the right questions: "Why is your quote $8k higher? What\'s included that the other guy doesn\'t cover?"' },
      { author: 'Brandon Hughes', date: '2026-03-02', text: 'The tariff data is terrifying and nobody talks about it. My contractor told me cabinets went up 50% because of tariffs and I thought he was exaggerating. He wasn\'t. The $10,900 extra per renovation is REAL and it\'s making an already expensive process even worse.' },
      { author: 'Anita Sharma', date: '2026-03-02', text: 'As someone who just bought her first home, this post is simultaneously the most useful and most terrifying thing I\'ve read today. The "63% went into debt" stat? I can see exactly how that happens. You start a project thinking $15k, then it\'s $20k, then $25k, and at that point you can\'t stop because you have half a bathroom.' },
      { author: 'Tom Fischer', date: '2026-03-02', text: 'Love that it\'s on-device and no account needed. Every renovation "tool" I\'ve used online is just a lead gen funnel that sells my number to contractors. I filled out one of those HomeAdvisor forms once and got 11 calls in 2 hours. Never again.' },
      { author: 'NativeFirst', date: '2026-03-02', text: 'Tom — that lead gen problem was literally one of the top reasons we built this as a native iOS app instead of a website. No email required, no phone number, no "enter your zip code to see results" that somehow results in six contractors calling you during dinner. You open the app, you get numbers. That\'s it.' },
      { author: 'Rachel Kim', date: '2026-03-02', text: 'Sent this to my husband. We\'ve been "planning" a kitchen remodel for 8 months and haven\'t called a single contractor because the price uncertainty gives us both anxiety. This is the kind of thing that would actually get us to start.' },
      { author: 'Danny O\'Brien', date: '2026-03-02', text: 'The shopping list feature is lowkey the most valuable part. Took my contractor\'s material list to Home Depot last year and half the items were marked up 40-60% over retail. Saved $3,200 by buying materials myself. If Renovise generates that kind of list automatically that\'s a game changer.' },
    ],
  },
  'ai-productivity-paradox-2026': {
    likes: 112,
    comments: [
      { author: 'Viktor Olsen', date: '2026-03-04', text: 'The METR study hit me hard. I genuinely thought I was faster with Copilot. Tracked my actual output for two weeks after reading this — turns out I was spending almost as much time reviewing and fixing AI suggestions as I saved generating them. The vibes really are a liar.' },
      { author: 'Amira Khoury', date: '2026-03-04', text: 'That Klarna timeline is chef\'s kiss journalism. Everyone was sharing that "700 employees replaced" headline like it was a victory. Nobody shared the "we focused too much on efficiency and quality dropped" follow-up. Funny how that works.' },
      { author: 'James Whitfield', date: '2026-03-04', text: 'I manage a team of 12 engineers. We rolled out Cursor last quarter. PRs went up 40%. Bugs went up 60%. Net effect: negative. We\'re now in the awkward position of having paid for tools that made us objectively worse. Great post, depressing conclusions.' },
      { author: 'NativeFirst R Team', date: '2026-03-04', text: 'James — we hear this from engineering leads constantly. The trick we\'ve found: restrict AI to boilerplate and scaffolding, keep humans on critical paths and architectural decisions. The 10% gain is real if you aim it correctly. The problem is when you point it at everything.' },
      { author: 'Sandra Liu', date: '2026-03-04', text: 'The "almost right" section should be required reading for every PM who says "just use AI to build it faster." Almost right code is the most expensive code in existence because it passes every review until it doesn\'t.' },
      { author: 'Marcus Webb', date: '2026-03-04', text: '66% spend more time fixing AI code than writing it from scratch. I literally laughed out loud because I did exactly this yesterday. Asked Claude to refactor a networking layer, spent 3 hours fixing the "refactored" version. Could have done it myself in 2.' },
      { author: 'Elena Petrova', date: '2026-03-04', text: 'The 41% more bugs stat from Uplevel is insane but also makes total sense. When code feels "free" to generate, you generate more of it. More code = more bugs. It\'s not a mystery, it\'s math.' },
      { author: 'Derek Tanaka', date: '2026-03-05', text: 'Shared this in our engineering Slack. 47 reactions in the first hour. The senior devs are all nodding. The junior devs are confused because they\'ve never known a world without AI suggestions. That generational gap is going to be a real problem.' },
      { author: 'NativeFirst R Team', date: '2026-03-05', text: 'Derek — that generational gap is something we think about a lot. Junior devs who learned with AI assistants are missing the debugging instinct that comes from manually tracing through code for hours. It\'s like learning to drive with cruise control — works great until you need to handle a skid.' },
      { author: 'Priya Mehta', date: '2026-03-05', text: 'The Google DORA stat is the one that keeps me up at night. For every 25% increase in AI adoption, system stability drops 7.2%. We are trading reliability for the illusion of speed. And reliability is the one thing users actually care about.' },
    ],
  },
  'vibe-coding-rumors-drama-reality-2026': {
    likes: 34,
    comments: [
      { author: 'Tom Ashworth', date: '2026-03-05', text: 'The matplotlib incident still makes me lose sleep. An AI AGENT wrote a hit piece about a human maintainer who rejected its PR. If someone pitched this as a Black Mirror episode two years ago they would have been told it\'s too unrealistic.' },
      { author: 'Katarina Novak', date: '2026-03-05', text: 'That Tea app disaster is genuinely horrifying. 72,000 images including passports and driver\'s licenses. And the founder\'s defense is "I don\'t know how to code." Cool, maybe don\'t build an app that handles sensitive data then??' },
      { author: 'Ryan Cooper', date: '2026-03-05', text: 'Karpathy moving to "agentic engineering" feels like a dad trying to rebrand after his catchphrase got too popular. Sorry Andrej, you\'re the vibe coding guy forever. That\'s your legacy now.' },
      { author: 'NativeFirst R Team', date: '2026-03-05', text: 'Ryan lol — to be fair, "agentic engineering" is a more accurate description of what serious developers are actually doing now. But yeah, it\'s like trying to rename a meme. The internet has decided.' },
      { author: 'Sana Mirza', date: '2026-03-05', text: 'You guys mentioned the matplotlib thing! I commented about it on your open source post last week. The fact that we now need to worry about AI agents retaliating against code reviewers is... not the 2026 I ordered.' },
      { author: 'Leo Tanaka', date: '2026-03-05', text: '"The vibes lied" should be on a t-shirt. Or a bumper sticker. Or tattooed on the forehead of every PM who says "AI will 10x our output." 19% slower but feeling 20% faster is the most human thing I\'ve ever read.' },
      { author: 'Jessica Huang', date: '2026-03-05', text: 'That Tailwind stat makes me physically angry every time I see it. 75 million downloads, 80% revenue drop. The entire AI industry is built on top of open source labor they refuse to compensate. It\'s digital colonialism with better branding.' },
      { author: 'Patrick Dunn', date: '2026-03-05', text: 'Linus Torvalds vibe coding a Python tool is the plot twist I didn\'t see coming. If the Linux guy is doing it, the rest of us have zero moral high ground left. We are all vibe coders now. Resistance is futile.' },
    ],
  },
  'claude-untapped-power-automations-2026': {
    likes: 28,
    comments: [
      { author: 'Kevin Zhao', date: '2026-03-07', text: 'The Microsoft thing is hilarious and nobody talks about it enough. They spent $13 billion on OpenAI, built Copilot, and their own engineers are using Claude Code. That\'s not a red flag, that\'s a red billboard on the highway.' },
      { author: 'Daniela Furst', date: '2026-03-07', text: 'Set up the n8n + MCP workflow yesterday after reading this. Took about 45 minutes. Asked Claude to build a workflow that monitors our Stripe webhooks, categorizes events, and posts summaries to Slack every morning. It built the whole thing in one shot. I just stared at my screen for a minute.' },
      { author: 'NativeFirst R Team', date: '2026-03-07', text: 'Daniela — that Stripe + Slack combo is one of our favorites too. Wait until you chain it with a weekly revenue summary that gets auto-generated into a Notion doc. That\'s when it starts feeling less like a tool and more like having a silent business partner.' },
      { author: 'Marcus Chen', date: '2026-03-07', text: 'The "uncomfortable part" section is what makes this blog different from every other AI hype outlet. Yes, one person replacing ten is incredible for the one person. For the other nine it\'s an existential crisis. Both things are true simultaneously and I appreciate you saying it out loud.' },
      { author: 'Tomás Herrera', date: '2026-03-07', text: '$3.65 for a complete MVP. Three dollars and sixty-five cents. I spent more on my morning coffee. The cost barrier to building software has effectively collapsed and I\'m not sure we\'ve fully processed what that means.' },
      { author: 'Aisha Okonkwo', date: '2026-03-07', text: 'That Layer 4 agent orchestration setup is exactly what I\'ve been trying to build. Sub-agents researching while the main agent codes? That\'s not pair programming, that\'s having an entire engineering department in your terminal. How stable is it in practice?' },
      { author: 'NativeFirst R Team', date: '2026-03-07', text: 'Aisha — honest answer: Layers 1-3 are rock solid. Layer 4 with sub-agents is powerful but you\'ll hit edge cases. Sometimes agents step on each other\'s work or one agent makes assumptions that break another\'s context. We run it daily but we also review everything before merging. It\'s more "supervised team" than "fully autonomous department" at this stage. Getting better every week though.' },
      { author: 'Chris Müller', date: '2026-03-07', text: 'The Zapier CTO building a system where a Slack emoji triggers Claude to generate and submit code is the most beautifully unhinged thing I\'ve read today. We are living in the future and the future runs on thumbs-up reactions.' },
      { author: 'Elise Johansson', date: '2026-03-07', text: 'One concern nobody raises about the solopreneur dream: what happens when the solo founder gets sick? Or goes on vacation? Or just needs a mental health day? If the business is one person + AI, there\'s zero redundancy. At least with a team someone can cover. With a "super individual" the bus factor is literally 1.' },
      { author: 'NativeFirst R Team', date: '2026-03-07', text: 'Elise — genuinely great point and something we think about. The answer is probably that the best solo setups are the ones where the automations run without you. If your n8n workflows, Zapier automations, and scheduled agents handle the day-to-day, you can step away for a week and the business keeps breathing. But that requires building for resilience from day one, not just for speed. Most solo founders are optimizing for speed right now.' },
      { author: 'Priya Narayanan', date: '2026-03-07', text: 'Just forwarded this to my CTO with the subject line "this is why I\'ve been asking for Claude Max licenses." Got approved in 11 minutes. This blog post just paid for itself lol.' },
      { author: 'Jake Morrison', date: '2026-03-07', text: 'The "Formula 1 car for grocery shopping" analogy is perfect. I\'ve been using Claude to write unit tests and format JSON for three months. Reading this feels like discovering my car has 7 more gears I never touched.' },
    ],
  },
  'programmers-vs-vibe-coders-2026': {
    likes: 203,
    comments: [
      { author: 'Alex Rivera', date: '2026-03-08', text: 'The "70% Trap" is now permanently lodged in my brain. I built a side project with Cursor last month — beautiful UI, everything worked, showed it to my friends. Then I tried adding Stripe integration and the whole thing collapsed like a house of cards. I couldn\'t debug it because I literally didn\'t understand the code. Ended up rewriting from scratch. This post should be mandatory reading.' },
      { author: 'Nina Kowalski', date: '2026-03-08', text: '"AI is like working with a really fast, overconfident intern." I manage three actual interns and this is so accurate it hurts. The code looks confident. The commit messages are confident. The tests (when they exist) look confident. And then the production database is publicly accessible. Confidence without competence is just expensive mistakes with better formatting.' },
      { author: 'Jake Morrison', date: '2026-03-08', text: 'The Tea Dating app story made me physically ill. 72,000 photos including IDs. And the fix was a five-minute Firebase config change that any junior developer would catch in code review. We are absolutely not ready for "everyone can be a developer" if this is what it produces.' },
      { author: 'Mario', date: '2026-03-08', text: 'Jake — yeah the Tea breach is the one that keeps me up at night because it\'s so preventable. Five minutes of reading the Firebase docs. That\'s it. That\'s the gap between a data breach and a secure app. The AI writes the code but it doesn\'t understand the consequences of what it wrote.' },
      { author: 'Sandra Liu', date: '2026-03-08', text: '"You know what to ask for" is the section I\'m sending to every non-technical founder who tells me they don\'t need a CTO because they have Cursor. The difference between "build me a user system" and "build me a user system with bcrypt, JWT with refresh rotation, rate-limited endpoints" is the difference between a product and a lawsuit.' },
      { author: 'Leo Tanaka', date: '2026-03-08', text: 'The METR study is the stat I keep coming back to. 19% SLOWER but developers THOUGHT they were 20% faster. We are literally lying to ourselves. The vibes are a drug and we are all addicted.' },
      { author: 'Daniela Furst', date: '2026-03-09', text: 'Hot take: this article is too kind to vibe coding. The Lovable stat isn\'t 1 in 10 planes with faulty landing gear. It\'s 1 in 10 planes with NO landing gear and the pilot doesn\'t know because they never learned to check. The analogy should be scarier because the reality is scarier.' },
      { author: 'Marcus Webb', date: '2026-03-09', text: 'I\'m a senior dev with 15 years experience. Started using Claude Code with proper setup (CLAUDE.md, hooks, TDD). My output literally tripled. My junior colleague uses it as a magic box and his bug rate quadrupled. Same tool. Same model. Completely different outcomes. This post explains why better than I could.' },
      { author: 'Priya Narayanan', date: '2026-03-09', text: 'Karpathy moving from "vibe coding" to "agentic engineering" is the character development arc nobody expected. Even the guy who coined the term is saying "actually, you should know what you\'re doing." If that\'s not the strongest argument for learning to code, I don\'t know what is.' },
      { author: 'Chris Müller', date: '2026-03-09', text: '"If you don\'t know what those words mean, AI can\'t help you care about them." This line absolutely wrecked me. Putting it on a Post-it on my monitor. Architecture, security, performance, edge cases — you can\'t delegate caring about things you\'ve never heard of.' },
      { author: 'Rachel Kim', date: '2026-03-10', text: 'The F1 analogy at the end is perfect. You don\'t need to be a mechanic to drive. But if you\'re racing, you better know the engine. I\'m sending this to every bootcamp grad I mentor. Learning to code isn\'t obsolete — it\'s more important than ever because now you need to review code that writes itself.' },
      { author: 'Mario', date: '2026-03-10', text: 'Rachel — exactly. And the cool part is: learning to code in 2026 is actually easier than ever because you have AI to help you learn. Use Claude to explain code, not just write it. Ask "why did you use this approach?" after every generation. That\'s how you build the understanding that makes you dangerous in the best way.' },
    ],
  },
  'claude-code-commands-i-actually-use': {
    likes: 178,
    comments: [
      { author: 'Kevin Zhao', date: '2026-03-10', text: 'The PreToolUse hook tip alone was worth the read. I set one up to block writes to our migrations/ folder and within two hours Claude tried to modify a migration. The hook caught it. Previously that would have gone straight to staging. You potentially just saved our production database.' },
      { author: 'Tomás Herrera', date: '2026-03-10', text: '"Stop using a Ferrari for grocery runs" is the section title of the year. I\'ve been using Opus for literally everything including renaming variables and adding console.logs. That\'s like hiring a surgeon to put on a Band-Aid. Just switched routine tasks to Haiku and my API bill dropped 60% overnight.' },
      { author: 'Samira Hassan', date: '2026-03-10', text: 'The Writer/Reviewer pattern found an auth bypass? Same model, different context, different blind spots. That\'s genuinely fascinating from a cognitive perspective. I wonder if this is similar to how human code reviews work — the reviewer literally can\'t see bugs in their own code but can spot them instantly in someone else\'s.' },
      { author: 'Mario', date: '2026-03-10', text: 'Samira — that\'s exactly the parallel. It\'s confirmation bias, but for AI. The writing session "knows" its code is correct because it wrote it. The review session just sees code and evaluates it cold. Same reason we do code reviews with humans — fresh eyes catch things the author physically can\'t see.' },
      { author: 'James Whitfield', date: '2026-03-10', text: 'Just created my first custom slash command (/project:review) using your template. 10 minutes to set up, already used it 4 times today. The severity rating (critical/warning/info) format is genius because it immediately tells me where to focus. Why didn\'t I do this months ago.' },
      { author: 'Dylan Park', date: '2026-03-10', text: 'The HANDOFF.md trick is so obvious in retrospect that I\'m angry at myself for not thinking of it. I\'ve been starting every session with a 200-word explanation of what I was doing yesterday. Now I just run /project:handoff at the end and /clear at the start. Context survives. Tokens saved. Brain cells preserved.' },
      { author: 'Aisha Okonkwo', date: '2026-03-11', text: 'Worktrees changed everything for me this week. I\'m running three Claude sessions in parallel right now — one building a feature, one writing tests for last week\'s code, one updating docs. They\'re all on separate branches. Zero interference. This is how multi-threaded development should feel.' },
      { author: 'Elise Johansson', date: '2026-03-11', text: 'The "hooks over rules" insight is the most important sentence in this article. We had "never commit directly to main" in our CLAUDE.md. Claude committed directly to main last week. Replaced it with a PreToolUse hook that blocks it. Problem solved permanently. Rules are suggestions. Hooks are laws.' },
      { author: 'Ben Okafor', date: '2026-03-11', text: 'The Medium article you referenced was fine but this is genuinely 10x better. Every command has a real story behind it, a mistake you made, and a link to go deeper. That\'s the difference between a listicle and something actually useful. Bookmarked and shared with my team.' },
      { author: 'Nadia Petrova', date: '2026-03-11', text: 'The TDD loop is my new default workflow. Write failing tests → commit → implement until they pass → commit. It sounds simple but the "commit the tests first" part is the non-obvious insight. Now if Claude\'s implementation is garbage I revert to the test commit and try again. The spec is preserved. This is how you use AI without losing control.' },
      { author: 'Mario', date: '2026-03-11', text: 'Nadia — YES. That\'s exactly it. The test commit is your safety net. It\'s the difference between "AI messed up, now what?" and "AI messed up, revert to the test commit, try again with a better prompt." Your spec survives Claude\'s mistakes. Simple concept, massive impact.' },
      { author: 'Raj Sharma', date: '2026-03-12', text: 'Please open-source your .claude/commands/ directory. The review command template alone would save hundreds of developers hours of setup. And if you can share the hooks config from settings.json too, even better. Would happily contribute to a community repo for this.' },
      { author: 'Viktor Olsen', date: '2026-03-12', text: '"That\'s like test-driving a car by sitting in the parking lot and honking the horn." I feel personally attacked lol. I\'ve been using Claude Code for 4 months and literally never set up a CLAUDE.md or custom command. Starting today. Wish me luck.' },
    ],
  },
  'same-app-twice-vibes-vs-code': {
    likes: 247,
    comments: [
      { author: 'Marcus Webb', date: '2026-03-12', text: 'This is the blog post the entire vibe coding debate has been waiting for. Not opinions. Not studies. An actual controlled experiment. Same developer, same AI, same app. 9 critical security issues vs 0. 0 tests vs 34. I\'m sending this to every founder who tells me "we don\'t need senior developers anymore."' },
      { author: 'Jake Morrison', date: '2026-03-12', text: 'JWT tokens set to expire in 365 DAYS. That\'s not a security flaw, that\'s a permanent backstage pass to everyone\'s financial data. And Claude generated that by default. This is the "silent failure" problem in action — it works, it just works in a way that\'s catastrophically wrong.' },
      { author: 'Sandra Liu', date: '2026-03-12', text: 'The 120 lines stat is the most important number in this post. 8% of the code was human-written. But that 8% was the database schema, RLS policies, JWT config, and edge case tests. In other words — 8% of the code was the part that prevented 100% of the security disasters. That ratio tells you everything about where human knowledge matters.' },
      { author: 'Mario', date: '2026-03-12', text: 'Sandra — you just said it better than I did in the entire post lol. 8% of the code preventing 100% of the security disasters is the TL;DR for this whole article. The question isn\'t "should AI write code?" It\'s "which 8% should a human write?"' },
      { author: 'Daniela Furst', date: '2026-03-12', text: 'The RLS being disabled on 2 of 4 tables is the Lovable CVE-2025-48757 all over again. Claude did EXACTLY what Lovable\'s generator did — disabled Row Level Security to avoid an auth error. It "fixed" the error by removing the lock from the front door. This is literally the Columbia University "agents suppress errors instead of handling them" failure pattern documented in real time.' },
      { author: 'Leo Tanaka', date: '2026-03-12', text: 'Hour 1 vibes: "I felt like a god." Hour 3 audit: "9 critical security vulnerabilities." This is the emotional roller coaster every vibe coder goes through except most of them never reach the audit phase. They just deploy at the "I feel like a god" stage. That\'s what makes this scary.' },
      { author: 'Tom Ashworth', date: '2026-03-12', text: 'The scorecard table is getting screenshot-ed and posted everywhere. "Ship-ready? HELL NO" next to "Ship-ready? YES" tells the whole story at a glance. Please keep making these comparison posts.' },
      { author: 'Priya Narayanan', date: '2026-03-12', text: 'The Veracode 45% failure rate matching your exact results is wild. You got critical flaws in 9 out of ~20 components. Veracode found 45% failure across 100+ models. Same number. Same pattern. It\'s not random — it\'s systemic. AI models are consistently insecure in the same ways and we need to stop being surprised by this.' },
      { author: 'Chris Müller', date: '2026-03-12', text: '"My own app just got roasted by my own AI." This is the funniest and saddest sentence in the entire post. The review Claude calling the builder Claude\'s code "fundamentally flawed" is the kind of AI-on-AI violence we didn\'t expect but absolutely deserve.' },
      { author: 'Elise Johansson', date: '2026-03-13', text: 'The point about the database schema being written by hand in Round 2 is crucial. The schema is the foundation. Get it wrong and everything built on top is wrong. AI can generate UI and CRUD and charts all day — but who designs the data model? That requires understanding the domain, not just the syntax.' },
      { author: 'Kevin Zhao', date: '2026-03-13', text: 'Did the vibes build on purpose to see how bad it would be and STILL got surprised by the results. That\'s the terrifying part. You KNEW it would have issues. You still didn\'t expect 9 criticals. Imagine someone who DOESN\'T know to check. They just deploy and wait for the breach notification.' },
      { author: 'Mario', date: '2026-03-13', text: 'Kevin — that\'s exactly what shook me. I expected problems. I didn\'t expect the env vars in the client bundle. I didn\'t expect the CSV export endpoint having zero auth. Those are the "silent failures" that scare me most — things that look fine, work fine, and will ruin you quietly.' },
      { author: 'Aisha Okonkwo', date: '2026-03-13', text: 'The "What I\'d Tell My Past Self" section is the most practical advice in any AI coding article I\'ve read. For the vibes build: just read the auth code. 5 minutes. For the code build: write the schema, security policies, and test specs. Let AI do the rest. That\'s not "learn to code." That\'s "learn the 8% that matters." Totally different proposition and way less intimidating.' },
      { author: 'Rachel Kim', date: '2026-03-13', text: 'This post completes the trilogy perfectly. Post 1 was the thesis (knowing code matters). Post 2 was the tools (here\'s how to use Claude Code properly). Post 3 is the proof (here\'s what happens when you do vs don\'t). Bookmark all three. Share all three. Make your PM read all three.' },
      { author: 'Dylan Park', date: '2026-03-13', text: 'Debug console.logs in production code leaking user objects with password hashes. That\'s not a security vulnerability, that\'s a confession written in JavaScript. The AI basically left a signed note saying "here\'s all your users\' data, you\'re welcome." And nobody would have caught it without reading the code.' },
    ],
  },
  'claude-dispatch-remote-ai-revolution': {
    likes: 312,
    comments: [
      { author: 'Kevin Zhao', date: '2026-03-20', text: 'The "Gym Report" story is killing me. I literally did the same thing yesterday — was at the barber getting a haircut when my manager pinged about a status report. Dispatched Claude from under the cape. Sent the report before my fade was done. My barber asked why I was grinning at my phone. Couldn\'t explain without sounding insane.' },
      { author: 'Samira Hassan', date: '2026-03-20', text: '"OpenClaw is for hackers. Dispatch is for everyone else." This is the most accurate one-liner about AI tooling I\'ve read all year. I tried OpenClaw for a week. Spent two days configuring Docker. Dispatch took me 90 seconds to set up and I\'m not exaggerating because I timed it too. The QR code thing is genius.' },
      { author: 'Dylan Park', date: '2026-03-20', text: 'The kid who Dispatched Claude to "make my computer say funny things" is the best thing I\'ve read this month. This is simultaneously adorable and terrifying. We\'re raising a generation that will think computers just... do what you text them. Which, apparently, they now do.' },
      { author: 'Marcus Webb', date: '2026-03-20', text: 'The no-notifications thing is genuinely the biggest miss. I Dispatched a report, forgot about it for 3 hours, then remembered at dinner and checked. It had been done for 2 hours and 47 minutes. Just sitting there. Finished. Patient. Waiting. Like a very diligent ghost. Anthropic PLEASE add push notifications this is the obvious fix.' },
      { author: 'Mario', date: '2026-03-20', text: 'Marcus — I filed the same feedback literally within the first hour. The irony of a "work from anywhere" feature that requires you to manually check if work is done is... something. I\'m sure it\'s coming. It\'s too obvious not to. For now I set a phone timer for 10 minutes after each Dispatch and check back. Primitive but functional.' },
      { author: 'Priya Sharma', date: '2026-03-20', text: 'Used Dispatch to prep meeting notes while walking my dog this morning. The dog was chasing squirrels. I was reviewing quarterly metrics on my phone. The meeting notes were being compiled on my Mac at home. Three completely independent activities happening simultaneously. We are living in the future and the future involves golden retrievers.' },
      { author: 'Tomás Herrera', date: '2026-03-20', text: 'The freelancer on the beach in Portugal is my spirit animal. I\'m a freelancer. I\'m currently in Lisbon. I am definitely not reading this blog post from a cafe while Claude compiles a client report on my Mac in Berlin. That would be irresponsible. Anyway, great feature, 10/10.' },
      { author: 'Chris Müller', date: '2026-03-20', text: 'The security comparison with OpenClaw is the most important part of this post. I was an early OpenClaw adopter and the Cisco report about malicious skills scared me off completely. Having everything sandboxed locally with explicit folder permissions is the right architecture. Yes it\'s less flexible. I\'ll take "less flexible but my data doesn\'t end up in a Telegram bot" every single time.' },
      { author: 'Rachel Kim', date: '2026-03-20', text: 'I am the Rachel in the "did I leave the oven on" story and I want to clarify that I was NOT panicking about a Google Doc. I was calmly and rationally verifying the state of my unsaved work. With urgency. While ordering a triple espresso. The point stands: Dispatch turns "oh no I have to go back" into a 15-second phone interaction. That alone is worth $20/month.' },
      { author: 'Elise Johansson', date: '2026-03-20', text: '"The prompt era was about talking to AI. The Dispatch era is about delegating to it." That\'s the line. That\'s the whole paradigm shift in one sentence. I\'m a PM and I\'ve been trying to explain to my engineering team why Dispatch matters to non-developers. This sentence does it better than my 20-minute presentation did.' },
      { author: 'Jake Morrison', date: '2026-03-20', text: 'The guy who used Dispatch to monitor deployments from a wedding is a legend and his wife deserves better. That said, I absolutely would do the same thing. I HAVE done the same thing, just with SSH and a terminal app and way more stress. At least Dispatch makes the irresponsible behavior comfortable.' },
      { author: 'Aisha Okonkwo', date: '2026-03-20', text: 'This is the first AI feature announcement that made me show my non-tech partner and have THEM get excited. She immediately asked "can I use it to organize our shared folders while I\'m at work?" Yes. Yes you can. And that reaction — from someone who has never written a line of code — is exactly why Dispatch matters more than any developer tool.' },
      { author: 'Ben Okafor', date: '2026-03-20', text: 'The 50/50 success rate on complex tasks is honest and I appreciate you not hiding it. This is clearly a research preview. But the 50% that works? Works REALLY well. And if this is the floor, the ceiling is terrifying (in the best way). Give it 6 months. This will be the feature everyone copies.' },
      { author: 'NativeFirst R Team', date: '2026-03-20', text: 'We\'ve been debating internally whether Dispatch makes our Remote Control blog post from last month obsolete. Consensus: no. Remote Control is for developers in Claude Code. Dispatch is for everyone in Cowork. They\'re siblings, not replacements. The exciting part is that Anthropic is clearly building toward a unified "your AI works everywhere you don\'t" vision. We\'re watching closely.' },
    ],
  },
  'programming-in-2031-our-predictions': {
    likes: 203,
    comments: [
      { author: 'Kevin Zhao', date: '2026-03-18', text: '"Human-in-the-Loop Specialist" just triggered my fight-or-flight response. I can already see the LinkedIn posts: "Thrilled to announce I\'ve been promoted to Senior Human-in-the-Loop Specialist at [company that just fired 40% of engineering]." The worst part? This will absolutely happen.' },
      { author: 'Samira Hassan', date: '2026-03-18', text: 'The legacy code prediction is the sleeper hit of this whole post. I work in financial services. We have COBOL that\'s been running since the 80s. Last month someone used Claude to document a module that three retired engineers couldn\'t explain. Management nearly fell out of their chairs. The "legacy modernization specialist" job title is already being discussed in our org. You\'re not predicting the future, you\'re describing our present.' },
      { author: 'Dylan Park', date: '2026-03-18', text: 'Prediction 2 is already happening and nobody wants to admit it. Our team went from 8 to 5 developers this year. Same output. Same quality. The three people who left weren\'t replaced — their work was absorbed by the remaining five using AI tools. My company called it "natural attrition." I call it exactly what you described: slowly, then all at once.' },
      { author: 'NativeFirst Team', date: '2026-03-18', text: 'Dylan — we debated whether to include Prediction 2 because it\'s genuinely uncomfortable. But uncomfortable truths are still truths. The nuance we want to emphasize: the five remaining developers aren\'t "cheaper replacements." They\'re the ones who understand the domain deeply enough to use AI effectively. That\'s the skill that survives.' },
      { author: 'Rachel Kim', date: '2026-03-18', text: 'The hot dog tangent is the most realistic part of this entire post. Every engineering team meeting I\'ve ever attended has devolved into an unrelated food debate at least once. The fact that you disclosed your hot-dog-sandwich position publicly is brave and I respect it even though you\'re wrong.' },
      { author: 'Tomás Herrera', date: '2026-03-18', text: 'The Great Prompt Collapse is the prediction I didn\'t expect to agree with so strongly. I\'m a prompt engineer right now. My literal job title. And I can feel it happening — every month, more of my prompts get embedded into tools and buttons and workflows. I\'m not writing prompts anymore, I\'m building the infrastructure that hides them. Which is great for job security in 2026 but terrifying for 2031.' },
      { author: 'Chris Müller', date: '2026-03-18', text: '"npm somehow gets worse" is the funniest line in any tech blog I\'ve read this year. The open source prediction is sadly the most realistic one. I maintain a mid-size OSS library and I already see it — people fork, modify with AI, never contribute back. My issue tracker has fewer human bug reports and more AI-generated "fix this" PRs that don\'t actually fix anything. The future is chaos and it\'s already here.' },
      { author: 'Priya Sharma', date: '2026-03-18', text: 'Prediction 5 (testing) resonates deeply. I\'m a QA lead and the amount of AI-generated code I see that "works" but has subtle logical errors is alarming. Last week a PR passed all automated tests but had a race condition that would only manifest under load. The AI wrote the code AND the tests — and the tests were designed around the same flawed assumptions as the code. Humans testing AI code is not optional. It\'s the whole game.' },
      { author: 'Jake Morrison', date: '2026-03-18', text: 'Revisiting this post in 2031 is a great idea. I\'m setting a literal calendar reminder. My prediction for what you\'ll get wrong: Prediction 3. Legacy code modernization won\'t be a "niche." It\'ll be the default. Every company over 20 years old will have an AI modernization initiative by 2029. It\'s too obvious not to.' },
      { author: 'Elise Johansson', date: '2026-03-18', text: '"AI doesn\'t replace understanding. It replaces typing." This is the most quotable line in the entire post and I\'m putting it on my team\'s Slack channel immediately. Simple, true, and it cuts through 90% of the panic. Understanding problems is the skill. Everything else is implementation detail — and implementation details are exactly what AI is good at.' },
      { author: 'Marcus Webb', date: '2026-03-18', text: 'The self-driving car comparison at the end is perfect. We\'ve been "5 years away" from AGI for 15 years now. Maybe AI plateaus. Maybe it doesn\'t. The safe bet is exactly what you said: be curious, be adaptable, understand problems. That advice would\'ve been good in 2016, it\'s good in 2026, and it\'ll be good in 2031 regardless of what the models do.' },
      { author: 'Aisha Okonkwo', date: '2026-03-18', text: 'This post has a vibe I wish more tech blogs had — honest without being doomer, funny without being dismissive, specific without being preachy. The pizza framing device works perfectly. More team roundtable posts please. Maybe invite some of us next time. I\'ll bring better pizza.' },
    ],
  },
  'your-prompts-are-not-skills-yet': {
    likes: 89,
    comments: [
      { author: 'Marcus Webb', date: '2026-03-16', text: 'The "saved prompt vs skill" distinction just reorganized my entire brain. I have 40+ prompts in Notion. Exactly THREE of them have variables. Those three are the ones I use daily. The other 37 are collecting digital dust. Time to promote or delete.' },
      { author: 'Sarah Chen', date: '2026-03-16', text: 'The Email Decoder example is literally my life. I work in a 500-person org where every email is a political novel wrapped in pleasantries. My "summarize this email" prompt just got rewritten with the {{my_tone}} variable and I\'m never going back. Diplomatic mode for execs, direct mode for my team. Chef\'s kiss.' },
      { author: 'James Whitfield', date: '2026-03-16', text: 'The Bug Report Whisperer is mine! Didn\'t expect to see my workflow in a blog post. For anyone wondering — yes, the diagnostic-first approach genuinely changed how I debug. Instead of trying 5 random fixes, I run 3 targeted checks and nail the root cause. Went from 45 min average debug time to under 15.' },
      { author: 'Mario', date: '2026-03-16', text: 'James — your skill was too good not to feature. The "doctor who runs tests vs doctor who guesses" line was yours and it perfectly captures the difference. Thanks for letting me share it.' },
      { author: 'Nadia Petrova', date: '2026-03-16', text: 'The community validation section hit different. I\'ve been using the same "generate social media posts" prompt for months thinking it was perfect. Showed it to two colleagues last week. Both said the output sounded robotic. I was blind to it because I wrote the prompt — confirmation bias is real even with AI tools.' },
      { author: 'Kevin Zhao', date: '2026-03-16', text: '"A saved prompt is a recipe you bookmarked. A skill is a recipe you\'ve cooked 50 times." Stealing this analogy for my team standup on Monday. We have a shared Notion of "approved prompts" that nobody iterates on. They\'re frozen in time from when someone wrote them in January. That\'s not a skill library, it\'s a museum.' },
      { author: 'Priya Sharma', date: '2026-03-16', text: 'The Meeting Killer skill — I just implemented something similar and my VP literally asked what changed. "Your meetings have decisions now." That\'s the feedback. Not "good meeting" or "nice agenda." The output changed because the prompt has constraints that force decisions instead of discussions.' },
      { author: 'Tomás Herrera', date: '2026-03-16', text: 'The skill stack concept is what I\'ve been calling "prompt pipelines" at work except nobody understood what I meant. Now I have a name for it and a blog post to send them. Research → Outline → Draft → Polish. Four skills. Two AIs. One tap. This is the workflow that makes PromptKit worth 10x its price.' },
      { author: 'Elise Johansson', date: '2026-03-16', text: 'Version history in v2 is the feature I didn\'t know I needed until you described it. I\'ve accidentally "improved" a prompt into being worse at least three times. Being able to diff versions and roll back would have saved me hours of figuring out what I broke.' },
      { author: 'Dylan Park', date: '2026-03-16', text: '"The prompt era was about writing. The skill era is about building." That\'s a t-shirt. Seriously though, this reframes the entire relationship with AI. I\'ve been treating every interaction as a conversation. Thinking of prompts as function calls — name, parameters, return value — changes everything about how you approach them.' },
      { author: 'Rachel Kim', date: '2026-03-16', text: 'Part 1 made me realize I had a problem. Part 2 just made me realize the problem was deeper than I thought. Saving prompts was step one. Parameterizing and iterating them is the actual work. Waiting impatiently for Part 3 about skill stacks in production — that\'s where the real productivity multipliers live.' },
      { author: 'Chris Müller', date: '2026-03-16', text: 'The practical exercise at the end is deceptively simple. Picked my most-used prompt (a code review one, similar to yours). Added three variables. Used it 10 more times. Found two edge cases I\'d been manually fixing every time. 20 minutes of work saved me 5 minutes per use. At 3 uses per day that\'s 25 minutes daily. Do the math on that across a year.' },
      { author: 'Aisha Okonkwo', date: '2026-03-16', text: 'Love how this connects to the Claude Code commands post. Custom slash commands ARE skills — they just live in a terminal. PromptKit brings the same concept to everyone. My marketing team doesn\'t need to know what a .md file is to build reusable prompt templates with variables. That\'s the unlock.' },
      { author: 'Ben Okafor', date: '2026-03-16', text: 'The "surprise the reader at least once" addition to the blog outline prompt after community feedback — THAT\'S the kind of micro-improvement that only happens when other humans test your prompts. An AI won\'t tell you your output is boring. Another human will. Community validation isn\'t optional, it\'s the quality layer.' },
      { author: 'Mario', date: '2026-03-16', text: 'Ben — exactly. And the embarrassing part is I genuinely thought my outline prompt was perfect. 12 versions of solo iteration and I missed the most obvious problem: the output was predictable. Two days of community feedback found what two months of personal use couldn\'t. That\'s the whole thesis of this post in one anecdote.' },
    ],
  },
  'where-do-your-ai-prompts-go-to-die': {
    likes: 156,
    comments: [
      { author: 'Kevin Zhao', date: '2026-03-13', text: 'The "prompts_final_v2_ACTUAL_FINAL.txt" line made me spit out my coffee because I have EXACTLY that file on my desktop right now. Except mine is called "chatgpt stuff NEW.txt" which is somehow worse. Signing up for the beta immediately.' },
      { author: 'Samira Hassan', date: '2026-03-13', text: '73% lose prompts regularly feels low tbh. I have prompts in Apple Notes, Google Docs, Notion, Slack DMs, screenshot in Photos (yes I\'m that person), and at least one email draft I sent to myself at 2 AM. The idea of having ONE app for all of this is almost too good to believe.' },
      { author: 'Marcus Webb', date: '2026-03-13', text: 'The workflow builder is the killer feature. I do exactly that blog post workflow manually — Perplexity for research, Claude for draft, ChatGPT for polish. Every. Single. Time. Having it as a saved workflow with one tap would probably save me 20 minutes per post.' },
      { author: 'Mario', date: '2026-03-13', text: 'Marcus — that workflow was literally the first one I built when we had the feature working. The moment I ran all four steps in sequence instead of manually copying between tabs I knew we were onto something. It\'s one of those "how did I live without this" moments.' },
      { author: 'Daniela Furst', date: '2026-03-13', text: 'The keyboard extension is sneaky brilliant. I didn\'t even think about wanting this until I saw the screenshot and now I can\'t un-want it. Being able to pull up my email template prompt from inside Mail without switching apps? That\'s the kind of native integration web apps literally cannot do.' },
      { author: 'Tomás Herrera', date: '2026-03-13', text: 'The community feed could be huge. There\'s a massive market for prompt sharing that\'s currently filled by sketchy websites charging $29 for prompt packs that are basically "write a blog post about {{topic}}" with fancy CSS. A free community built into the app is so much better.' },
      { author: 'Elise Johansson', date: '2026-03-13', text: 'The privacy angle matters more than people think. My prompts contain client names, project details, competitive analysis queries. Sending all of that to some random prompt-sharing website? No thanks. Offline-first with optional sync is the right architecture for this.' },
      { author: 'Leo Tanaka', date: '2026-03-13', text: '"2.3 hours per week on prompt management" translates to about $5,000/year for a senior developer. That\'s not a convenience problem, that\'s an ROI calculation. PromptKit is $2.99/month or $29.99 lifetime. If it saves 120 hours a year, the math is stupid obvious.' },
      { author: 'Nadia Petrova', date: '2026-03-13', text: 'The variable system is exactly what I\'ve been hacking together with TextExpander. Except TextExpander doesn\'t know about AI targets, doesn\'t have a community, and costs $50/year. If PromptKit does variables + launch + community for less, I\'m switching instantly.' },
      { author: 'Rachel Kim', date: '2026-03-13', text: 'I showed this to my marketing team. Three people independently said "oh my god I need this." We currently share prompts via a Notion page that nobody updates and everyone duplicates. A shared community where we can save each other\'s prompts to personal libraries is exactly right.' },
      { author: 'Jake Morrison', date: '2026-03-13', text: 'Honest question: is there a Teams tier coming? Our startup has 8 people and we all use different prompts for the same tasks. A shared workspace where the team lead publishes "approved" prompts and everyone can save them would be worth paying for.' },
      { author: 'Mario', date: '2026-03-13', text: 'Jake — Teams is planned for v2! Shared prompt libraries within a workspace, team admin can publish prompts visible to all members, per-seat pricing. It\'s exactly the use case you described. For now, the community feed gets you halfway there — your team can follow each other and save shared prompts. Proper team workspaces are next.' },
      { author: 'Chris Müller', date: '2026-03-13', text: 'The fact that it runs natively on both iPhone AND Mac with real sync is what separates this from the 47 "prompt manager" Chrome extensions that popped up last year and disappeared. Native apps stick around. Web extensions don\'t. Build it right or don\'t build it.' },
      { author: 'Aisha Okonkwo', date: '2026-03-13', text: 'Starting with 200+ curated prompts during onboarding is so smart. Cold-starting a prompt library is the "I\'ll set it up later" that never happens. Having prompts pre-loaded from day one means you\'re immediately getting value instead of staring at an empty screen.' },
      { author: 'Ben Okafor', date: '2026-03-13', text: 'Just audited my own prompt situation after reading this. 31 prompts across 6 different apps. Two of them were duplicates with slight variations because I couldn\'t find the originals. I am absolutely the target market for this and I am absolutely signing up for the beta. Where\'s the waitlist?' },
    ],
  },
  'gambling-addiction-tech-responsibility': {
    likes: 68,
    comments: [
      { author: 'Daniel Hayes', date: '2026-02-20', text: 'This is incredibly important. The stats about suicide rates are heartbreaking. Thank you for bringing attention to this.' },
      { author: 'Sarah Mitchell', date: '2026-02-20', text: 'As someone in recovery, I can confirm the existing apps are terrible. Would love to see what NativeFirst builds.' },
      { author: 'Kevin Patel', date: '2026-02-21', text: 'The fact that this would be free shows real integrity. Most companies would monetize addiction recovery immediately.' },
      { author: 'Laura Bennett', date: '2026-02-21', text: 'Shared this with my counseling practice. The research here is solid and the message is powerful.' },
    ],
  },
};
